### ISSUE TITLE
Querying Tasks by their code_name

### ISSUE THREAD

**Issue by cessor** [iron-io/iron_worker_python#33]
Hi, I am not sure whether this is the right place to bring this up, but I was wondering whether it was possible to query tasks by their code_name. I have multiple task types as workers installed in the same project and would like to get only those tasks that are of a certain code type. The API already provides this feature:

    GET /projects/{Project ID}/tasks?code_name={CODE NAME}

I am not sure whether chaning the signature of ```IronWorker.tasks(self, scheduled=False)``` would be the way to go. So far I helped myself by patching the Ironworker like this:

```
def tasks_by_code_name(self, code_name):
    tasks = []
    resp = self.client.get("tasks?code_name={0}".format(code_name))
    raw_tasks = resp["body"]
    raw_tasks = raw_tasks["tasks"]
    for raw_task in raw_tasks:
        tasks.append(Task(raw_task))
    return tasks

IronWorker.tasks_by_code_name = tasks_by_code_name
```

What do you think, what would be the right way to provide such a feature? Should I flesh this out and send a pull request?

**Comment by nikhilm** [comment]
#37 fixed this.
