### ISSUE TITLE
PyPi package has outdated codes 

### ISSUE THREAD

**Issue by masnun** [iron-io/iron_worker_python#53]
I downloaded the package from here: 

https://pypi.python.org/pypi/iron-worker

And as you can see the code is messed up: 

![screen shot 2015-12-17 at 8 20 20 pm](https://cloud.githubusercontent.com/assets/191543/11871742/b2fcf2da-a4fb-11e5-86b9-190308fe4903.png)

I was working with Python 3.4.3 and I got errors that hint about mixture of tabs and spaces. 

The issue seems to have been fixed on the latest master: https://github.com/iron-io/iron_worker_python/blob/master/iron_worker.py#L494 

So I believe a quick push to PyPi should fix this.

**Comment by ulandj** [comment]
Hi @masnun ,
The lib have been pushed to PyPi

Thanks
