### ISSUE TITLE
PyPi Package is broken (again)

### ISSUE THREAD

**Issue by masnun** [iron-io/iron_worker_python#58]
I previously opened an issue about it -- https://github.com/iron-io/iron_worker_python/issues/53 

One of my colleagues is getting similar issue again. 

```
 File "/Users/username/myenv/lib/python3.5/site-packages/iron_worker.py", line 489
    body = {}
            ^
TabError: inconsistent use of tabs and spaces in indentation
```

It would be really great if you guys could avoid shipping broken packages on PyPi. Or if it is broken, please push a newer version with a fix.

**Comment by ulandj** [comment]
could you let me know what version of the client using your colleague? The latest version is 1.3.7 in PyPi.
Judging by the logs of the error above you are using an old version of the client, because the code `body = {}` are in line 533 and 545 now

**Comment by masnun** [comment]
He installed it from a requirements.txt file of a project. I will ask him to switch to the latest and see if it works.

**Comment by nikhilm** [comment]
@masnun any updates? Otherwise I'll be closing this in a couple of days.

**Comment by masnun** [comment]
This looks resolved now.
